# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='user_id',
            new_name='user',
        ),
    ]
