# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
        ('travel_buddy', '0002_auto_20180222_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Destination', to='logreg.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='datefrom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dateto',
            field=models.CharField(max_length=255),
        ),
    ]
